[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
tests = true
skip-lint = true

[programs.devnet]
space_core = "DKRg9skUuewV1wdbVD6tpnoHtbWWy2Chq7EKdpPRY6Eh"

[programs.localnet]
space_core = "DKRg9skUuewV1wdbVD6tpnoHtbWWy2Chq7EKdpPRY6Eh"

# [registry]
# url = "https://api.apr.dev"
# Commented out - program not registered in Anchor registry but is deployed on devnet

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
